
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def open_script(self):
        ...

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 686)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/industrial-robot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.script = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.open_script)
        self.script.setGeometry(QtCore.QRect(180, 208, 281, 301))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.script.setFont(font)
        self.script.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.script.setStyleSheet("background-color: rgb(24, 143, 255);\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.script.setIcon(icon1)
        self.script.setIconSize(QtCore.QSize(90, 90))
        self.script.setObjectName("script")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, -1, 1041, 141))
        self.frame.setStyleSheet("background-color: rgb(34, 40, 49);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 30, 101, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: rgb(118, 171, 174);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.control_panel = QtWidgets.QPushButton(self.frame)
        self.control_panel.setGeometry(QtCore.QRect(750, 30, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.control_panel.setFont(font)
        self.control_panel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.control_panel.setStyleSheet("background-color: rgb(223, 223, 14);\n"
"color: rgb(0, 0, 0);")
        self.control_panel.setAutoDefault(False)
        self.control_panel.setDefault(False)
        self.control_panel.setFlat(False)
        self.control_panel.setObjectName("control_panel")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(160, 60, 191, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(160, 40, 71, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(9, 139, 1041, 491))
        self.frame_2.setStyleSheet("background-color: rgb(49, 54, 63);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 68, 281, 301))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(137, 255, 124);\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/construction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(484, 10, 71, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(270, -30, 501, 541))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/robotic-hand.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.frame_2.raise_()
        self.pushButton.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LEXUS"))
        self.pushButton.setText(_translate("MainWindow", "SCRIPT"))
        self.pushButton_3.setText(_translate("MainWindow", "Connect"))
        self.control_panel.setText(_translate("MainWindow", "Control Panel"))
        self.label_3.setText(_translate("MainWindow", "IP Address"))
        self.pushButton_2.setText(_translate("MainWindow", "BLOCKLY"))
        self.label_2.setText(_translate("MainWindow", "Applications"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
